services:
  warp:
    build:
      context: .
      network: host
    container_name: warp-proxy
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
    restart: always
    environment:
      - ROTATE_INTERVAL=3600
      - http_proxy=http://127.0.0.1:15732
      - https_proxy=http://127.0.0.1:15732
      - HTTP_PROXY=http://127.0.0.1:15732
      - HTTPS_PROXY=http://127.0.0.1:15732
